### ISSUE TITLE
Need to limit the potential run time to avoid flaming CPUs

### ISSUE THREAD

**Issue by NicholasRostant** [SirSharpest/Rubiks-Cube-Solver#3]

**Comment by SirSharpest** [comment]
Roughly looking at it I think there is a max possibility of 43,252,003,274,489,856,000 combinations that are available. 

In addition to using IDS A* and limiting the depth, I also think something may be needed to slow down calculations made and perhaps skip a few system cycles so not to overload a system for particularly awkward puzzles

**Comment by SirSharpest** [comment]
Apply new thermal paste and flaming CPU should be solved. Issue resolved
